require "user.plugins"
require "user.keymaps"
require "user.options"
-- require "user.plugins"
require "user.colorscheme"
require "user.treesitter"
require "user.nvim-tree"
require "user.cmp"
require "user.autopairs"
require "user.comments"
require "user.telescope"
require "user.gitsigns"
require "user.lsp"
-- require "user.bufferline"
require "user.winbar"
require "user.lualine"
require "user.trouble"
require "user.auto-cmd"
require "user.blankline"
require "user.jabs"
