#!/usr/bin/env bash
code --install-extension aaron-bond.better-comments
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bierner.markdown-mermaid
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DanSnow.vscode-dockerfilelint
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ee92.folderize
code --install-extension esbenp.prettier-vscode
code --install-extension googlecloudtools.cloudcode
code --install-extension Gruntfuggly.todo-tree
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nelnet-velocity.velocity-workflow
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension sainnhe.forest-theme
code --install-extension sdras.night-owl
code --install-extension shidhincr.theme-dracula-italics
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
