#!/usr/bin/env bash
code --install-extension aaron-bond.better-comments
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension DanSnow.vscode-dockerfilelint
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ee92.folderize
code --install-extension esbenp.prettier-vscode
code --install-extension golang.go
code --install-extension googlecloudtools.cloudcode
code --install-extension GraphQL.vscode-graphql
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension JakeBecker.elixir-ls
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension Prisma.prisma
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension sdras.night-owl
code --install-extension shidhincr.theme-dracula-italics
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension toba.vsfire
code --install-extension tomoyukim.vscode-mermaid-editor
code --install-extension Unity.unity-debug
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zxh404.vscode-proto3
