export DOTFILES="$HOME/dotfiles"
export ZSH_CONFIG="$DOTFILES/zsh"

HISTFILE=~/.zsh_history
setopt appendhistory

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
# compinit
_comp_options+=(globdots)		# Include hidden files.

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

autoload -U add-zsh-hook

source "$ZSH_CONFIG/zsh-functions"

zsh_add_file "setup-nvm"

# Source environemtn variables from each file
# in $DOTFILES/vars that has a .vars.sh file name
for file in $ZSH_CONFIG/vars/**/*.vars.sh; do
  source ${file}
done

# Source aliases from each file
# in $DOTFILES/aliases that has a .alias.sh file name
for file in $ZSH_CONFIG/aliases/**/*.alias.sh; do
  source ${file}
done

# Start starship
eval "$(starship init zsh)"

# Useful functions
source "$ZSH_CONFIG/zsh-functions"

zsh_add_file "setup-nvm"
# zsh_add_file "zsh-vim-mode"

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"

bindkey -s '^n' 'nvim .^M'

